package com.mindq.ai.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Provider-agnostic response from an AI completion call.
 * Contains the generated text and token usage statistics.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AICompletionResponse {

    /** The AI-generated text content. */
    private String content;

    /** Which model actually answered (echoed back from the provider). */
    private String model;

    /** Number of tokens in the prompt. */
    private int promptTokens;

    /** Number of tokens generated by the AI. */
    private int completionTokens;

    /** Total tokens used (prompt + completion). */
    private int totalTokens;
}
